### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by ttzl279** [simonflueckiger/tesserocr-windows_build#11]
I can not use this out of the box with Python 3.8. I've fiddled around for a while now, but it seems without being able to compile the libraries myself, it's not going to work.

Any chance of adding out-of-the-box Python 3.8 support?

**Comment by GZLHZ** [comment]
same request, waiting support.

**Comment by literence** [comment]
waiting support

**Comment by PM-yanmao** [comment]
waiting support

**Comment by PM-yanmao** [comment]
waiting support

**Comment by lockieRichter** [comment]
Agree.

**Comment by EhsanKia** [comment]
Has anyone figured out how to compile it for 3.8?

**Comment by tb102122** [comment]
any updates? having the same issue.

**Comment by ApurvaDani** [comment]
Require support for 3.8

**Comment by wjx0912** [comment]
waiting support

**Comment by 2press** [comment]
@simonflueckiger Can you help us out?

**Comment by Callan-Git** [comment]
Require support for 3.9

**Comment by bytetriper** [comment]
same request but for 3.10

**Comment by simonflueckiger** [comment]
Sorry for the very long wait everyone. The old build pipeline was in dire need of a proper refactor. The build of Tesseract was depending on [CPPAN](https://github.com/cppan/cppan) which is not maintained anymore. Instead of opting for [Software Network](https://github.com/SoftwareNetwork/sw) (the successor of CPPAN), I decided to go with the more tried and tested [vcpkg](https://github.com/microsoft/vcpkg). This should now make it really easy for me to update and maintain the Windows binaries for new builds of tesserocr and Tesseract.

You can find the latest release in [tesserocr v2.5.2 (tesseract 4.1.1)](https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.5.2-tesseract-4.1.1) which is built for Python 3.6, 3.7, 3.8, 3.9, 3.10. I know that for most of you this probably comes too late, sorry about that. Nonetheless, I would very much appreciate if any of you could give it a test-drive and report back here if it works as intended so I can close this issue.

**Comment by tb102122** [comment]
@simonflueckiger see details in #12
